version: '3.8'

services:
  hub:
    container_name: ErisHub
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    volumes:
      - ./ErisHub/appsettings.Development.json:/app/appsettings.Development.json
      - ./ErisHub/serverconfig.Development.json:/app/serverconfig.Development.json
    build:
        target: debug
  bot:
    container_name: ErisHub.DiscordBot
    environment:
      - BOT_ENV=Development
    volumes:
      - ./ErisHub.DiscordBot/config.json:/app/config.json
      - ./ErisHub.DiscordBot/config.Development.json:/app/config.Development.json
      - ./ErisHub.DiscordBot/db:/app/db
    build:
        target: debug
