// <auto-generated />
using System;
using ErisHub.DiscordBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ErisHub.DiscordBot.Migrations
{
    [DbContext(typeof(BotContext))]
    partial class BotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("ErisHub.DiscordBot.Database.Models.NewcomerConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong?>("NewcomerRoleId");

                    b.HasKey("Id");

                    b.ToTable("NewcomerConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1
                        });
                });

            modelBuilder.Entity("ErisHub.DiscordBot.Database.Models.NewcomerSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("ChannelId");

                    b.Property<ulong>("EmoteId");

                    b.Property<ulong>("MessageId");

                    b.Property<ulong>("RoleId");

                    b.HasKey("Id");

                    b.ToTable("NewcomerSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
